stages:
  - build
  - deploy

# 构建工作
build:
  stage: build
  image: node:18
  cache:
    paths:
      - node_modules/
    script:
      - npm install -g pnpm  
      - pnpm install  
      - pnpm run docs:build
    artifacts:
      paths:
        - docs/.vitepress/dist
      expire_in: 1 week

# 部署工作
deploy:
  stage: deploy
  image: alpine/git
  dependencies:
    - build
  script:
    - pnpm run deploy
  environment:
    name: main
  only:
    - main
